#!/bin/sh
set -x
git pull
git reset # make sure we aren't commiting anything else
git add posts/*
if ! git diff --cached --exit-code --quiet
    then git commit -m 'automatic commit as part of deploy'
    else echo "no posts to commit"
fi
set -e
stack exec teallabs -- build
branch=$(git rev-parse --abbrev-ref HEAD)
git checkout gh_pages
cp -r _site/* .
git add .
if ! git diff --cached --exit-code --quiet
    then git commit -m "regenerate website"
    else echo "no _site changes to commit"
fi
git push
git checkout $branch
