#!/bin/sh
set -x
git pull
git add posts/*
git commit -am 'automatic commit as part of deploy'
git push
set -e
stack exec teallabs -- build
rsync -avz --delete --rsh "ssh -i $HOME/.ssh/id_nearlyfreespeech" _site/ bergey_teallabs@ssh.phx.nearlyfreespeech.net:
