I've found [[https://gist.github.com/jboner/2841832][this table of latency numbers "every programmer" should know]] quite helpful over the last few years.  I've also been a bit nervous using it, as the years pass.  Is it still accurate?  Has any hardware gotten faster in the last 12 years?  The big changes are in SSDs and networking.  More discussion of these, measurements, and data sources, after the table.

| L1 cache reference                         | 1 ns       |                     |
| L2 cache reference                         | 3 ns       |                     |
| L3 cache reference                         | 10 ns      |                     |
| RAM reference                              | 100 ns     |                     |
| send 1k bytes over 100 Gbps network        | 100 ns     | throughput          |
| send 1M bytes over 100 Gbps network        | 100 μs    | throughput          |
| read an arbitrary 4k block from SSD (NVMe) | 50-100 μs |                     |
| read 100 4k blocks from SSD (NVMe)         | 100 μs    | in parallel         |
| read 1 MB from SSD, in parallel            | 300 μs    | 3.5 GB/s throughput |
| network round trip within same rack        | 300 μs    |                     |
| round trip to another zone in same region  | 1 ms       |                     |
| spinning disk seek                         | 10 ms      |                     |
| read 1 MB sequentially from spinning disk  | 20 ms      |                     |
| Send packet NYC->Tokyo->NYC                | 175 ms     |                     |

SSDs have gotten faster, both single read latency and throughput. In the table above, I tried to touch on the fact that SSDs are parallel, while keeping the focus on latency, not tipping too far into throughput. To use the full bandwidth, I needed to have 100 requests in flight, but those need not be reading adjacent blocks. Fewer, larger requests can also utilize the full bandwidth.  I used [[https://fio.readthedocs.io/en/latest/fio_doc.html][fio]] to issue read requests, using =buffered=0= and =ioengine=io_uring= to minimize overhead and try to measure disk performance, not the file system or OS page cache.  I ran [[https://github.com/iovisor/bcc/blob/master/tools/biolatency.py][biolatency]] during the test to check that the expected number of reads were reaching the disk, and that =fio= was observing roughly the same latency as the kernel.  I was led to both tools by [[https://www.brendangregg.com/blog/2020-07-15/systems-performance-2nd-edition.html][Brenden Gregg's book]].  Full script at the end.  Spinning disk numbers come from the 2012 table.

I measured round trip times within a cloud region with =ping=.  These were taken in Google's region =us-central1=, using [[https://cloud.google.com/compute/docs/instances/placement-policies-overview][a placement policy]] to ensure two VMs were on the same rack.  AWS provides a [[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-strategies.html#placement-groups-cluster][similar option to locate VMs closer together.]]  The round-the-world time comes from [[https://wondernetwork.com/pings/New%20York/Tokyo][Wonder Network]].

different zones, same region:
#+begin_src
50 packets transmitted, 50 received, 0% packet loss, time 50134ms
rtt min/avg/max/mdev = 0.670/0.797/1.310/0.085 ms
#+end_src

same rack:
#+begin_src
50 packets transmitted, 50 received, 0% packet loss, time 50168ms
rtt min/avg/max/mdev = 0.165/0.305/0.711/0.081 ms
#+end_src

Amazon says [[https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/availability-zones.html#:~:text=Availability%20Zones%20in%20a%20Region,with%20single%2Ddigit%20millisecond%20latency.][zones in a region can be 100 km apart,]] so 1ms between zones is likely dominated by speed of light over that distance. I don’t know where the 0.3 ms between VMs in a single rack comes from. () says that a network switch only adds 12 us, for example. Time spent in the Linux IP / udp stack? In the hypervisor, waiting for our turn on the network?

The 2012 table has a row for throughput is gigabit network, and of course that hasn’t changed. Common servers today have network connections with much higher throughput, though. I can rent a machine from AWS with 100 Gbps, and I gather one can buy machines with 400. 

https://chipsandcheese.com/memory-latency-data/ has interesting graphs of cache sizes and latencies for recent CPUs.  [[https://github.com/dicksites/KUtrace][Dick Sites]] provides code to measure on your hardware, and [[https://www.amazon.com/Understanding-Software-Addison-Wesley-Professional-Computing/dp/0137589735][his book]] explains some of the difficulties of getting accurate mesurements.  CPUs have also added more cores, and *larger* caches, which are not reflected in this table of latencies.  Nor have I tried to capture pipelining, data- or instruction-level parallelism, mostly because I don't know enough.  Like SSDs and network requests, maximally efficient use of CPUs requires giving them work that they can process in parallel.

cite:
- leanstore
- blog post about AWS ping times
- bandwidth-delay product paper with the 12 μs router times

  #+begin_src sh
    #!/usr/bin/env bash

CMD="fio --runtime=60 --time_based --clocksource=clock_gettime --rw=randread --size=5g --filename=fio.tmp  --name=randread --ioengine=io_uring --buffered=0"

for size in 1k 2k 4k 8k 16k 64k 256k 1M; do
    biolatency &
    pid=$!
    $CMD --bs=$size
    kill -INT $pid
done

for parallel in 1 3 10 32 100 316 1000; do
    biolatency &
    pid=$!
    $CMD --max-jobs=3 --iodepth=$parallel  --bs=4k
    kill -INT $pid
done
  #+end_src
